<?php
 /***************************************************************************
 * Appshore                                                                 *
 * http://www.appshore.com                                                  *
 * This file written by Brice Michel  bmichel@appshore.com                  *
 * Copyright (C) 2004-2009 Brice Michel                                     *
 ***************************************************************************/


require_once ( APPSHORE_LIB.SEP.'class.base.php');

class administration_company_base extends lib_base
{

    function __construct()
    {
    	$this->appTable 		= 'company';
    	$this->appRecordId		= 'company_id';
    	$this->appRecordName	= 'company_name';
    	$this->appOrderBy		= 'company_name';
    	$this->appAscDesc		= 'desc';
    	$this->appName 			= 'administration_company';
    	$this->appNameSingular	= 'administration_company';
    	$this->appLabel 		= 'Company';
    	$this->appLabelSingular = 'Company';
    	$this->appXSL	 		= 'administration.company';
    	$this->appRole 			= 'administration';

		parent::__construct();
    }

    function menus()
    {
        $GLOBALS['appshore']->add_xsl('lib.base');
        $GLOBALS['appshore']->add_xsl($this->appXSL);

		execMethod('administration.base.menus', '', true);

		$GLOBALS['appshore']->add_appmenu($this->appLabel, 'Information', 'administration.company_base.view');

		if ( $GLOBALS['appshore']->rbac->check($this->appRole, RBAC_ADMIN ) )
        {
			//$GLOBALS['appshore']->add_appmenu($this->appLabel, 'Email configuration', 'administration.emailer.view');
			$GLOBALS['appshore']->add_appmenu($this->appLabel, 'Usage statistics', 'administration.statistics.start');

			if( PAYMENT_MENU == true && $GLOBALS['appshore_data']['current_user']['language_id'] != 'ja')
			{
				//$GLOBALS['appshore']->add_appmenu($this->appLabel, 'Your orders', 'administration.orders_base.start');
				//$GLOBALS['appshore']->add_appmenu($this->appLabel, 'Your invoices', 'administration.invoices_base.start');
				$GLOBALS['appshore']->add_appmenu($this->appLabel, 'Upgrade your subscription', 'administration.'.PRIVATE_LABEL.'subscription.upgrade');
			}
			$GLOBALS['appshore']->add_appmenu($this->appLabel, 'Close your account', 'administration.'.PRIVATE_LABEL.'subscription.close');
		}

	}

    function start()
    {
		$this->menus();

		$result[$this->appName] = '';
		$result['action'][$this->appName] = 'start';
		$result['recordset'] = $_SESSION[$this->appName];

		return $result;
    }

	// view one profile
    function search( $args=null)
    {
    	return $this->view($args);
    }

	// view one profile
    function view( $args=null)
    {
    	// only the current company profile must be accessible
    	$args['company_id'] = $GLOBALS['appshore_data']['my_company']['company_id'];

		return parent::view( $args);
    }


	// view one profile
    function edit( $args=null)
    {
    	// only the current company profile must be accessible
    	$args['company_id'] = $GLOBALS['appshore_data']['my_company']['company_id'];

		$result = parent::edit( $args);

		// don't want to see list of users generated by default
		unset( $result['users']);

		return $result;
    }
}
