
tinyMCE.init({
	mode : "specific_textareas",
	editor_selector : "mceEditor",
	theme : "advanced",
	plugins : "AppShore,searchreplace,spellchecker,fullscreen",
	theme_advanced_buttons1 : "undo,redo,separator,search,replace,separator,spellchecker,fontselect,fontsizeselect,bold,italic,underline,strikethrough,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,bullist,numlist,separator,outdent,indent,separator,forecolor,backcolor,separator,link,unlink,separator,removeformat,AppShoreTemplates,AppShoreSignatures,fullscreen",
	theme_advanced_buttons2 : "",
//	theme_advanced_buttons1 : "newdocument,separator,cut,copy,paste,separator,undo,redo,separator,search,replace,separator,spellchecker,AppShoreTemplates,AppShoreSignatures,fullscreen",
//	theme_advanced_buttons2 : "fontselect,fontsizeselect,bold,italic,underline,strikethrough,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,bullist,numlist,separator,outdent,indent,separator,forecolor,backcolor,separator,link,unlink,image,separator,removeformat",
	theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	//theme_advanced_path_location : "bottom",
	theme_advanced_resize_horizontal : false,
	theme_advanced_resizing : false,
	nonbreaking_force_tab : true,
	forced_root_block : false,
	force_p_newlines : false,
	remove_linebreaks : false,
	force_br_newlines : true,
	remove_trailing_nbsp : false,
	convert_urls : false,	
	spellchecker_rpc_url : basepath+'/includes/tiny_mce/plugins/spellchecker/rpc.php',
	spellchecker_languages : "+English=en,Español=es,Français=fr",
	language : "en",	
	apply_source_formatting : true,
	auto_resize : true,
	sid : sid 
});
