
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'department_top_id';
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'manager_id';
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'assistant_id';
UPDATE db_fields SET search_sequence = '2' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'department_top_id';
UPDATE db_fields SET search_sequence = '0' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'country_billing';
UPDATE db_fields SET bulk_sequence = '0' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'country_billing';

REPLACE INTO `db_blocks` (`app_name`, `form_name`, `block_id`, `block_name`, `is_title`, `columns`, `block_sequence`) VALUES
('administration_users', 'bulk', '13qfxwi7vfi8w', 'bulk', 'N', 2, 2),
('administration_users', 'edit', '1ixcu5lf30asg', 'Note', 'Y', 1, 11),
('administration_users', 'edit', '1q6htfo3inesk', 'Personal Information', 'Y', 2, 6),
('administration_users', 'edit', '1r2irncvnack0', 'Footer', 'N', 2, 13),
('administration_users', 'edit', '1s9mtebmfoo0o', 'Header', 'N', 2, 2),
('administration_users', 'edit', '2brr1b6lkeasw', 'Preferences', 'Y', 2, 8),
('administration_users', 'edit', 'kfpueqebytc0', 'Setup', 'Y', 2, 10),
('administration_users', 'edit', 'sif2w2u11r4g', 'Main', 'N', 2, 4),
('administration_users', 'popup_edit', '1op6wuzxu9fo', 'Header', 'N', 1, 1),
('administration_users', 'popup_edit', 'dxofjnamwhs0', 'Note', 'N', 1, 4),
('administration_users', 'popup_edit', 'vhl12f6951c4', 'Main', 'N', 2, 3),
('administration_users', 'popup_view', '1cz0xswt9tq84', 'Main', 'N', 2, 3),
('administration_users', 'popup_view', '1kfjzfu4tbb4s', 'Header', 'N', 1, 1),
('administration_users', 'popup_view', 'cqkdsoiy8hwg', 'Note', 'N', 1, 4),
('administration_users', 'view', '1bcrvou4l58g40cogogkos44c', 'Footer', 'N', 2, 11),
('administration_users', 'view', '1burjizs6wsg80swcsg0sogok', 'Personal Information', 'Y', 2, 6),
('administration_users', 'view', '2unkxwlk320wk40skskwogoc', 'Note', 'Y', 1, 9),
('administration_users', 'view', '9izhpab9el8g0888kwk044kk', 'Header', 'N', 2, 2),
('administration_users', 'view', 'f8b5x8hv2z48ksc0gsks4kws', 'Main', 'N', 2, 4),
('administration_users', 'view', 'k6v9hw2z1n48cwcw8kwksw4s', 'Preferences', 'Y', 2, 8);

REPLACE INTO `db_fields` (`app_name`, `table_name`, `field_name`, `is_custom`, `is_computed`, `field_type`, `field_label`, `field_height`, `field_default`, `related_table`, `related_id`, `related_name`, `related_filter`, `is_search`, `is_readonly`, `is_mandatory`, `is_unique`, `is_visible`, `search_sequence`, `result_sequence`, `result_class`, `bulk_sequence`, `bulk_side`, `bulk_block_id`, `view_sequence`, `view_side`, `view_block_id`, `edit_sequence`, `edit_side`, `edit_block_id`, `popup_search_sequence`, `popup_result_sequence`, `popup_view_sequence`, `popup_view_side`, `popup_view_block_id`, `popup_edit_sequence`, `popup_edit_side`, `popup_edit_block_id`, `linked_sequence`) VALUES
('administration_users', 'users', 'app_name', 'N', 'N', 'DD', 'Default application', 1, 'api', 'db_applications', 'app_name', 'app_label', 'where is_visible = "Y" and status_id = "A" order by app_label', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 1, 'L', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'assistant_id', 'N', 'N', 'DD', 'Assistant', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 1, 'R', '13qfxwi7vfi8w', 6, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 6, 'R', 'sif2w2u11r4g', 5, 0, 6, 'R', '1cz0xswt9tq84', 6, 'R', 'vhl12f6951c4', 0),
('administration_users', 'users', 'birthdate', 'N', 'N', 'DA', 'Date of birth', 1, '0000-00-00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '1burjizs6wsg80swcsg0sogok', 1, 'L', '1q6htfo3inesk', 0, 0, 0, 'L', '1pz3r2tgoyo0s', 0, 'L', 'sr1hn2m5y684', 0),
('administration_users', 'users', 'charset_id', 'N', 'N', 'DD', 'Character set', 1, 'UTF-8', 'global_charsets', 'charset_id', 'charset_name', 'order by charset_name', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 2, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'confirm_delete', 'N', 'N', 'CH', 'Confirm delete', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '13qfxwi7vfi8w', 5, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 5, 'L', '2brr1b6lkeasw', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'created', 'N', 'N', 'TS', 'Created', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 2, 'L', '1bcrvou4l58g40cogogkos44c', 0, 'L', '', 0, 0, 0, 'L', '1lmo16svlpdwo', 0, 'L', '', 0),
('administration_users', 'users', 'created_by', 'N', 'N', 'RR', 'Created by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'currency_id', 'N', 'N', 'DD', 'Currency', 1, 'USD', 'global_currencies', 'currency_id', 'currency_name', ' order by currency_name', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 4, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 4, 'L', '2brr1b6lkeasw', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'department_id', 'N', 'N', 'DD', 'Department', 1, '', 'departments', 'department_id', 'department_name', '', 'N', 'N', 'N', 'N', 'Y', 4, 7, 'grid_left', 3, 'R', '13qfxwi7vfi8w', 4, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 4, 'R', 'sif2w2u11r4g', 3, 3, 4, 'R', '1cz0xswt9tq84', 4, 'R', 'vhl12f6951c4', 4),
('administration_users', 'users', 'email', 'N', 'N', 'WM', 'Email', 1, '', '', '', '', '', 'N', 'N', 'Y', 'Y', 'Y', 3, 6, 'grid_left', 0, 'L', '', 5, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 5, 'L', 'sif2w2u11r4g', 0, 6, 5, 'L', '1cz0xswt9tq84', 5, 'L', 'vhl12f6951c4', 7),
('administration_users', 'users', 'fax', 'N', 'N', 'TE', 'Fax', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 6, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 6, 'L', 'sif2w2u11r4g', 0, 0, 6, 'L', '1cz0xswt9tq84', 6, 'L', 'vhl12f6951c4', 0),
('administration_users', 'users', 'first_names', 'N', 'N', 'VF', 'First name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 1, 'L', 'sif2w2u11r4g', 0, 0, 1, 'L', '1cz0xswt9tq84', 1, 'L', 'vhl12f6951c4', 2),
('administration_users', 'users', 'full_name', 'N', 'N', 'TE', 'Full name', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 2, 2, 'grid_left', 0, 'L', '', 0, 'L', '9gba8zpqcnwg', 0, 'L', '', 2, 2, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'initial_role_id', 'N', 'N', 'DD', 'Initial role', 1, '', 'roles', 'role_id', 'role_name', 'order by role_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 2, 'L', '13qfxwi7vfi8w', 0, 'L', '', 1, 'R', 'kfpueqebytc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'is_salespeople', 'N', 'N', 'CH', 'Sales people', 1, 'N', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '13qfxwi7vfi8w', 3, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 3, 'R', 'sif2w2u11r4g', 0, 0, 3, 'R', '1cz0xswt9tq84', 3, 'R', 'vhl12f6951c4', 0),
('administration_users', 'users', 'language_id', 'N', 'N', 'DD', 'Language', 1, 'en', 'global_languages', 'language_id', 'language_name', ' order by language_id', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 1, 'R', '2brr1b6lkeasw', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'last_login', 'N', 'N', 'TS', 'Last login', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 7, 'grid_center', 0, 'L', '', 1, 'L', '1bcrvou4l58g40cogogkos44c', 1, 'L', '1r2irncvnack0', 0, 0, 0, 'L', '1lmo16svlpdwo', 0, 'L', '', 0),
('administration_users', 'users', 'last_name', 'N', 'N', 'VF', 'Last name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 1, 'R', 'sif2w2u11r4g', 0, 0, 1, 'R', '1cz0xswt9tq84', 1, 'R', 'vhl12f6951c4', 3),
('administration_users', 'users', 'last_password_change', 'N', 'N', 'TS', 'Last password change', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 1, 'R', '1bcrvou4l58g40cogogkos44c', 1, 'R', '1r2irncvnack0', 0, 0, 0, 'R', '1lmo16svlpdwo', 0, 'L', '', 0),
('administration_users', 'users', 'locale_date_id', 'N', 'N', 'DD', 'Date format', 1, 'en_US', 'global_locales_date', 'date_id', 'date_label', ' order by date_label', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 3, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'locale_time_id', 'N', 'N', 'DD', 'Time format', 1, 'en_US', 'global_locales_time', 'time_id', 'time_label', ' order by time_label', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 4, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 4, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'manager_id', 'N', 'N', 'DD', 'Manager', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 2, 'R', '13qfxwi7vfi8w', 5, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 5, 'R', 'sif2w2u11r4g', 4, 0, 5, 'R', '1cz0xswt9tq84', 5, 'R', 'vhl12f6951c4', 0),
('administration_users', 'users', 'mobile', 'N', 'N', 'TE', 'Mobile', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 5, 'grid_left', 0, 'L', '', 3, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 3, 'L', 'sif2w2u11r4g', 0, 5, 3, 'L', '1cz0xswt9tq84', 3, 'L', 'vhl12f6951c4', 6),
('administration_users', 'users', 'nbrecords', 'N', 'N', 'DD', 'Lines displayed', 1, '10', 'global_lines', 'line_id', 'line_name', 'order by line_name', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 5, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 5, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'note', 'N', 'N', 'ML', 'Note', 5, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '2unkxwlk320wk40skskwogoc', 1, 'L', '1ixcu5lf30asg', 0, 0, 1, 'L', 'cqkdsoiy8hwg', 1, 'L', 'dxofjnamwhs0', 0),
('administration_users', 'users', 'password', 'N', 'N', 'TE', 'Password', 1, '', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'phone', 'N', 'N', 'TE', 'Phone', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 4, 'grid_left', 0, 'L', '', 4, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 4, 'L', 'sif2w2u11r4g', 0, 4, 4, 'L', '1cz0xswt9tq84', 4, 'L', 'vhl12f6951c4', 5),
('administration_users', 'users', 'private_email', 'N', 'N', 'WM', 'Private email', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', '1burjizs6wsg80swcsg0sogok', 1, 'R', '1q6htfo3inesk', 0, 0, 0, 'R', '1pz3r2tgoyo0s', 0, 'R', 'sr1hn2m5y684', 0),
('administration_users', 'users', 'private_mobile', 'N', 'N', 'TE', 'Private mobile', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', '1burjizs6wsg80swcsg0sogok', 2, 'R', '1q6htfo3inesk', 0, 0, 0, 'R', '1pz3r2tgoyo0s', 0, 'R', 'sr1hn2m5y684', 0),
('administration_users', 'users', 'private_phone', 'N', 'N', 'TE', 'Private phone', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', '1burjizs6wsg80swcsg0sogok', 2, 'L', '1q6htfo3inesk', 0, 0, 0, 'L', '1pz3r2tgoyo0s', 0, 'L', 'sr1hn2m5y684', 0),
('administration_users', 'users', 'reset_password', 'N', 'Y', 'CH', 'Reset password', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 3, 'L', '13qfxwi7vfi8w', 0, 'L', '', 2, 'L', 'kfpueqebytc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'salutation', 'N', 'N', 'TE', 'Salutation', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 2, 'L', 'sif2w2u11r4g', 0, 0, 2, 'L', '1cz0xswt9tq84', 2, 'L', 'vhl12f6951c4', 0),
('administration_users', 'users', 'send_welcome_email', 'N', 'Y', 'CH', 'Send welcome email', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 2, 'L', '13qfxwi7vfi8w', 0, 'L', '', 1, 'L', 'kfpueqebytc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'skin_id', 'N', 'N', 'DD', 'Skin', 1, 'default', 'global_skins', 'skin_id', 'skin_name', ' order by skin_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 0, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'status_id', 'N', 'N', 'DD', 'User status', 1, 'A', 'users_statuses', 'status_id', 'status_name', 'where status_id in ("A","D") order by status_name', 'N', 'N', 'Y', 'N', 'Y', 5, 8, 'grid_left', 1, 'L', '13qfxwi7vfi8w', 2, 'R', '9izhpab9el8g0888kwk044kk', 1, 'R', '1s9mtebmfoo0o', 0, 0, 0, 'R', '1bwu9iw9qois8', 0, 'R', '1lp4pvgw4f8k0', 8),
('administration_users', 'users', 'theme_id', 'N', 'N', 'DD', 'Theme', 1, 'default', 'global_themes', 'theme_id', 'theme_name', ' order by theme_name', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 2, 'L', '2brr1b6lkeasw', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'timezone_id', 'N', 'Y', 'DD', 'Timezone', 1, '225', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 3, 'L', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'title', 'N', 'N', 'TE', 'Title', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 2, 'R', 'sif2w2u11r4g', 0, 0, 2, 'R', '1cz0xswt9tq84', 2, 'R', 'vhl12f6951c4', 0),
('administration_users', 'users', 'updated', 'N', 'N', 'TS', 'Updated', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 2, 'R', '1bcrvou4l58g40cogogkos44c', 0, 'R', '', 0, 0, 0, 'R', '1lmo16svlpdwo', 0, 'L', '', 0),
('administration_users', 'users', 'updated_by', 'N', 'N', 'RR', 'Updated by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'user_id', 'N', 'N', 'RK', 'User identifier', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', '9izhpab9el8g0888kwk044kk', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'user_name', 'N', 'N', 'VF', 'User name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'Y', 'Y', 1, 1, 'grid_left', 0, 'L', '', 1, 'L', '9izhpab9el8g0888kwk044kk', 1, 'L', '1s9mtebmfoo0o', 1, 1, 1, 'L', '1kfjzfu4tbb4s', 1, 'L', '1op6wuzxu9fo', 1);

