update db_fields set field_label = "Character set" where table_name = "users" and field_name = "charset_id";
UPDATE db_fields SET field_label = 'Manager', related_table = 'users', related_id = 'user_id', related_name = 'full_name' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'manager_id';
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'department_top_id';
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'manager_id';
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'assistant_id';
UPDATE db_fields SET search_sequence = '2' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'department_top_id';
UPDATE db_fields SET search_sequence = '0' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'country_billing';
UPDATE db_fields SET bulk_sequence = '0' WHERE db_fields.app_name = 'administration_departments' AND db_fields.field_name = 'country_billing';
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'department_id';
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'manager_id';
UPDATE db_fields SET field_type = 'DD' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'assistant_id';
UPDATE db_fields SET result_sequence = '0' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'first_names';
UPDATE db_fields SET result_sequence = '0' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'last_name';
UPDATE db_fields SET result_sequence = '2' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'full_name';
UPDATE db_fields SET result_sequence = '7' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'department_id';
UPDATE db_fields SET search_sequence = '0' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'first_names';
UPDATE db_fields SET search_sequence = '0' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'last_name';
UPDATE db_fields SET search_sequence = '2' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'full_name';
UPDATE db_fields SET search_sequence = '3' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'email';
UPDATE db_fields SET popup_result_sequence = '0' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'first_names';
UPDATE db_fields SET popup_result_sequence = '0' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'last_name';
UPDATE db_fields SET popup_result_sequence = '2' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'full_name';
UPDATE db_fields SET popup_search_sequence = '0' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'first_names';
UPDATE db_fields SET popup_search_sequence = '0' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'last_name';
UPDATE db_fields SET popup_search_sequence = '2' WHERE db_fields.app_name = 'administration_users' AND db_fields.field_name = 'full_name';
