DROP VIEW IF EXISTS `global_locales` ;
DROP VIEW IF EXISTS `global_skins` ;
		
DELETE FROM db_blocks where app_name = 'administration_users';
INSERT INTO `db_blocks` (`app_name`, `form_name`, `block_id`, `block_name`, `is_title`, `columns`, `block_sequence`) VALUES
('administration_users', 'bulk', '13qfxwi7vfi8w', 'bulk', 'N', 2, 2),
('administration_users', 'edit', '1ixcu5lf30asg', 'Note', 'Y', 1, 11),
('administration_users', 'edit', '1q6htfo3inesk', 'Personal Information', 'Y', 2, 6),
('administration_users', 'edit', '1r2irncvnack0', 'Footer', 'N', 2, 13),
('administration_users', 'edit', '1s9mtebmfoo0o', 'Header', 'N', 2, 2),
('administration_users', 'edit', '2brr1b6lkeasw', 'Preferences', 'Y', 2, 8),
('administration_users', 'edit', 'kfpueqebytc0', 'Setup', 'Y', 2, 10),
('administration_users', 'edit', 'sif2w2u11r4g', 'Main', 'N', 2, 4),
('administration_users', 'popup_edit', '1op6wuzxu9fo', 'Header', 'N', 1, 1),
('administration_users', 'popup_edit', 'dxofjnamwhs0', 'Note', 'N', 1, 4),
('administration_users', 'popup_edit', 'vhl12f6951c4', 'Main', 'N', 2, 3),
('administration_users', 'popup_view', '1cz0xswt9tq84', 'Main', 'N', 2, 3),
('administration_users', 'popup_view', '1kfjzfu4tbb4s', 'Header', 'N', 1, 1),
('administration_users', 'popup_view', 'cqkdsoiy8hwg', 'Note', 'N', 1, 4),
('administration_users', 'view', '1bcrvou4l58g40cogogkos44c', 'Footer', 'N', 2, 11),
('administration_users', 'view', '1burjizs6wsg80swcsg0sogok', 'Personal Information', 'Y', 2, 6),
('administration_users', 'view', '2unkxwlk320wk40skskwogoc', 'Note', 'Y', 1, 9),
('administration_users', 'view', '9izhpab9el8g0888kwk044kk', 'Header', 'N', 2, 2),
('administration_users', 'view', 'f8b5x8hv2z48ksc0gsks4kws', 'Main', 'N', 2, 4),
('administration_users', 'view', 'k6v9hw2z1n48cwcw8kwksw4s', 'Preferences', 'Y', 2, 8);

DELETE FROM db_fields where app_name = 'administration_users';
INSERT INTO `db_fields` (`app_name`, `table_name`, `field_name`, `is_custom`, `is_computed`, `field_type`, `field_label`, `field_height`, `field_default`, `related_table`, `related_id`, `related_name`, `related_filter`, `is_search`, `is_readonly`, `is_mandatory`, `is_unique`, `is_visible`, `search_sequence`, `result_sequence`, `result_class`, `bulk_sequence`, `bulk_side`, `bulk_block_id`, `view_sequence`, `view_side`, `view_block_id`, `edit_sequence`, `edit_side`, `edit_block_id`, `popup_search_sequence`, `popup_result_sequence`, `popup_view_sequence`, `popup_view_side`, `popup_view_block_id`, `popup_edit_sequence`, `popup_edit_side`, `popup_edit_block_id`, `linked_sequence`) VALUES
('administration_users', 'users', 'app_name', 'N', 'N', 'DD', 'Default application', 1, 'api', 'db_applications', 'app_name', 'app_label', 'where is_visible = "Y" and status_id = "A" order by app_label', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 1, 'L', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'assistant_id', 'N', 'N', 'RR', 'Assistant', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 1, 'R', '13qfxwi7vfi8w', 6, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 6, 'R', 'sif2w2u11r4g', 6, 0, 6, 'R', '1cz0xswt9tq84', 6, 'R', 'vhl12f6951c4', 0),
('administration_users', 'users', 'birthdate', 'N', 'N', 'DA', 'Date of birth', 1, '0000-00-00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '1burjizs6wsg80swcsg0sogok', 1, 'L', '1q6htfo3inesk', 0, 0, 0, 'L', '1pz3r2tgoyo0s', 0, 'L', 'sr1hn2m5y684', 0),
('administration_users', 'users', 'charset_id', 'N', 'N', 'DD', 'Charset id', 1, 'UTF-8', 'global_charsets', 'charset_id', 'charset_name', 'order by charset_name', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 2, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'confirm_delete', 'N', 'N', 'CH', 'Confirm delete', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '13qfxwi7vfi8w', 5, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 5, 'L', '2brr1b6lkeasw', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'created', 'N', 'N', 'TS', 'Created', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 2, 'L', '1bcrvou4l58g40cogogkos44c', 0, 'L', '', 0, 0, 0, 'L', '1lmo16svlpdwo', 0, 'L', '', 0),
('administration_users', 'users', 'created_by', 'N', 'N', 'RR', 'Created by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'currency_id', 'N', 'N', 'DD', 'Currency', 1, 'USD', 'global_currencies', 'currency_id', 'currency_name', ' order by currency_name', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 4, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 4, 'L', '2brr1b6lkeasw', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'department_id', 'N', 'N', 'RR', 'Department', 1, '', 'departments', 'department_id', 'department_name', '', 'N', 'N', 'N', 'N', 'Y', 4, 0, 'grid_left', 3, 'R', '13qfxwi7vfi8w', 4, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 4, 'R', 'sif2w2u11r4g', 4, 4, 4, 'R', '1cz0xswt9tq84', 4, 'R', 'vhl12f6951c4', 4),
('administration_users', 'users', 'email', 'N', 'N', 'WM', 'Email', 1, '', '', '', '', '', 'N', 'N', 'Y', 'Y', 'Y', 0, 6, 'grid_left', 0, 'L', '', 5, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 5, 'L', 'sif2w2u11r4g', 0, 7, 5, 'L', '1cz0xswt9tq84', 5, 'L', 'vhl12f6951c4', 7),
('administration_users', 'users', 'fax', 'N', 'N', 'TE', 'Fax', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 6, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 6, 'L', 'sif2w2u11r4g', 0, 0, 6, 'L', '1cz0xswt9tq84', 6, 'L', 'vhl12f6951c4', 0),
('administration_users', 'users', 'first_names', 'N', 'N', 'VF', 'First name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 2, 2, 'grid_left', 0, 'L', '', 1, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 1, 'L', 'sif2w2u11r4g', 2, 2, 1, 'L', '1cz0xswt9tq84', 1, 'L', 'vhl12f6951c4', 2),
('administration_users', 'users', 'full_name', 'N', 'N', 'TE', 'Full name', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '9gba8zpqcnwg', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'initial_role_id', 'N', 'N', 'DD', 'Initial role', 1, '', 'roles', 'role_id', 'role_name', 'order by role_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 2, 'L', '13qfxwi7vfi8w', 0, 'L', '', 1, 'R', 'kfpueqebytc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'is_salespeople', 'N', 'N', 'CH', 'Sales people', 1, 'N', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '13qfxwi7vfi8w', 3, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 3, 'R', 'sif2w2u11r4g', 0, 0, 3, 'R', '1cz0xswt9tq84', 3, 'R', 'vhl12f6951c4', 0),
('administration_users', 'users', 'language_id', 'N', 'N', 'DD', 'Language', 1, 'en', 'global_languages', 'language_id', 'language_name', ' order by language_id', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 1, 'R', '2brr1b6lkeasw', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'last_login', 'N', 'N', 'TS', 'Last login', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 7, 'grid_center', 0, 'L', '', 1, 'L', '1bcrvou4l58g40cogogkos44c', 1, 'L', '1r2irncvnack0', 0, 0, 0, 'L', '1lmo16svlpdwo', 0, 'L', '', 0),
('administration_users', 'users', 'last_name', 'N', 'N', 'VF', 'Last name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 3, 3, 'grid_left', 0, 'L', '', 1, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 1, 'R', 'sif2w2u11r4g', 3, 3, 1, 'R', '1cz0xswt9tq84', 1, 'R', 'vhl12f6951c4', 3),
('administration_users', 'users', 'last_password_change', 'N', 'N', 'TS', 'Last password change', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 1, 'R', '1bcrvou4l58g40cogogkos44c', 1, 'R', '1r2irncvnack0', 0, 0, 0, 'R', '1lmo16svlpdwo', 0, 'L', '', 0),
('administration_users', 'users', 'locale_date_id', 'N', 'N', 'DD', 'Date format', 1, 'en_US', 'global_locales_date', 'date_id', 'date_label', ' order by date_label', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 3, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'locale_time_id', 'N', 'N', 'DD', 'Time format', 1, 'en_US', 'global_locales_time', 'time_id', 'time_label', ' order by time_label', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 4, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 4, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'manager_id', 'N', 'N', 'RR', 'Manager', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 2, 'R', '13qfxwi7vfi8w', 5, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 5, 'R', 'sif2w2u11r4g', 5, 0, 5, 'R', '1cz0xswt9tq84', 5, 'R', 'vhl12f6951c4', 0),
('administration_users', 'users', 'mobile', 'N', 'N', 'TE', 'Mobile', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 5, 'grid_left', 0, 'L', '', 3, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 3, 'L', 'sif2w2u11r4g', 0, 6, 3, 'L', '1cz0xswt9tq84', 3, 'L', 'vhl12f6951c4', 6),
('administration_users', 'users', 'nbrecords', 'N', 'N', 'DD', 'Lines displayed', 1, '10', 'global_lines', 'line_id', 'line_name', 'order by line_name', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 5, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 5, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'note', 'N', 'N', 'ML', 'Note', 5, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '2unkxwlk320wk40skskwogoc', 1, 'L', '1ixcu5lf30asg', 0, 0, 1, 'L', 'cqkdsoiy8hwg', 1, 'L', 'dxofjnamwhs0', 0),
('administration_users', 'users', 'password', 'N', 'N', 'TE', 'Password', 1, '', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'phone', 'N', 'N', 'TE', 'Phone', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 4, 'grid_left', 0, 'L', '', 4, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 4, 'L', 'sif2w2u11r4g', 0, 5, 4, 'L', '1cz0xswt9tq84', 4, 'L', 'vhl12f6951c4', 5),
('administration_users', 'users', 'private_email', 'N', 'N', 'WM', 'Private email', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', '1burjizs6wsg80swcsg0sogok', 1, 'R', '1q6htfo3inesk', 0, 0, 0, 'R', '1pz3r2tgoyo0s', 0, 'R', 'sr1hn2m5y684', 0),
('administration_users', 'users', 'private_mobile', 'N', 'N', 'TE', 'Private mobile', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', '1burjizs6wsg80swcsg0sogok', 2, 'R', '1q6htfo3inesk', 0, 0, 0, 'R', '1pz3r2tgoyo0s', 0, 'R', 'sr1hn2m5y684', 0),
('administration_users', 'users', 'private_phone', 'N', 'N', 'TE', 'Private phone', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', '1burjizs6wsg80swcsg0sogok', 2, 'L', '1q6htfo3inesk', 0, 0, 0, 'L', '1pz3r2tgoyo0s', 0, 'L', 'sr1hn2m5y684', 0),
('administration_users', 'users', 'reset_password', 'N', 'Y', 'CH', 'Reset password', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 3, 'L', '13qfxwi7vfi8w', 0, 'L', '', 2, 'L', 'kfpueqebytc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'salutation', 'N', 'N', 'TE', 'Salutation', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', 'f8b5x8hv2z48ksc0gsks4kws', 2, 'L', 'sif2w2u11r4g', 0, 0, 2, 'L', '1cz0xswt9tq84', 2, 'L', 'vhl12f6951c4', 0),
('administration_users', 'users', 'send_welcome_email', 'N', 'Y', 'CH', 'Send welcome email', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 2, 'L', '13qfxwi7vfi8w', 0, 'L', '', 1, 'L', 'kfpueqebytc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'skin_id', 'N', 'N', 'DD', 'Skin', 1, 'default', 'global_skins', 'skin_id', 'skin_name', ' order by skin_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', 'k6v9hw2z1n48cwcw8kwksw4s', 0, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'status_id', 'N', 'N', 'DD', 'User status', 1, 'A', 'users_statuses', 'status_id', 'status_name', 'where status_id in ("A","D") order by status_name', 'N', 'N', 'Y', 'N', 'Y', 5, 8, 'grid_left', 1, 'L', '13qfxwi7vfi8w', 1, 'R', '9izhpab9el8g0888kwk044kk', 1, 'R', '1s9mtebmfoo0o', 0, 0, 0, 'R', '1bwu9iw9qois8', 0, 'R', '1lp4pvgw4f8k0', 8),
('administration_users', 'users', 'theme_id', 'N', 'N', 'DD', 'Theme', 1, 'default', 'global_themes', 'theme_id', 'theme_name', ' order by theme_name', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 2, 'L', '2brr1b6lkeasw', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'timezone_id', 'N', 'Y', 'DD', 'Timezone', 1, '225', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'L', 'k6v9hw2z1n48cwcw8kwksw4s', 3, 'L', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('administration_users', 'users', 'title', 'N', 'N', 'TE', 'Title', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', 'f8b5x8hv2z48ksc0gsks4kws', 2, 'R', 'sif2w2u11r4g', 0, 0, 2, 'R', '1cz0xswt9tq84', 2, 'R', 'vhl12f6951c4', 0),
('administration_users', 'users', 'updated', 'N', 'N', 'TS', 'Updated', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 2, 'R', '1bcrvou4l58g40cogogkos44c', 0, 'R', '', 0, 0, 0, 'R', '1lmo16svlpdwo', 0, 'L', '', 0),
('administration_users', 'users', 'updated_by', 'N', 'N', 'RR', 'Updated by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'user_id', 'N', 'N', 'RK', 'User identifier', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', '9gba8zpqcnwg', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('administration_users', 'users', 'user_name', 'N', 'N', 'VF', 'User name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'Y', 'Y', 1, 1, 'grid_left', 0, 'L', '', 1, 'L', '9izhpab9el8g0888kwk044kk', 1, 'L', '1s9mtebmfoo0o', 1, 1, 1, 'L', '1kfjzfu4tbb4s', 1, 'L', '1op6wuzxu9fo', 1);

DELETE FROM db_blocks where app_name = 'preferences_lookandfeel';
INSERT INTO `db_blocks` (`app_name`, `form_name`, `block_id`, `block_name`, `is_title`, `columns`, `block_sequence`) VALUES
('preferences_lookandfeel', 'view', 'hi2u1ickxmh340ssog40w0k0', 'Theme', 'Y', 1, 5),
('preferences_lookandfeel', 'edit', '10ragq2617itc', 'Theme', 'Y', 1, 5),
('preferences_lookandfeel', 'view', 'bi2qxal31txucckgc4sosc4s', 'Locale', 'Y', 2, 4),
('preferences_lookandfeel', 'edit', '1h90e2frullvk', 'Locale', 'Y', 2, 4),
('preferences_lookandfeel', 'view', '8xfiiba91u5qossows8c4g0s', 'Main', 'N', 2, 2),
('preferences_lookandfeel', 'edit', '12238nyd9hxc0', 'Main', 'N', 2, 2);

DELETE FROM db_fields where app_name = 'preferences_lookandfeel';
INSERT INTO `db_fields` (`app_name`, `table_name`, `field_name`, `is_custom`, `is_computed`, `field_type`, `field_label`, `field_height`, `field_default`, `related_table`, `related_id`, `related_name`, `related_filter`, `is_search`, `is_readonly`, `is_mandatory`, `is_unique`, `is_visible`, `search_sequence`, `result_sequence`, `result_class`, `bulk_sequence`, `bulk_side`, `bulk_block_id`, `view_sequence`, `view_side`, `view_block_id`, `edit_sequence`, `edit_side`, `edit_block_id`, `popup_search_sequence`, `popup_result_sequence`, `popup_view_sequence`, `popup_view_side`, `popup_view_block_id`, `popup_edit_sequence`, `popup_edit_side`, `popup_edit_block_id`, `linked_sequence`) VALUES
('preferences_lookandfeel', 'users', 'confirm_delete', 'N', 'N', 'CH', 'Confirm delete', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '13qfxwi7vfi8w', 2, 'R', '8xfiiba91u5qossows8c4g0s', 2, 'R', '12238nyd9hxc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'locale_date_id', 'N', 'N', 'DD', 'Format date', 1, 'en_US', 'global_locales_date', 'date_id', 'date_label', ' order by date_label', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', 'bi2qxal31txucckgc4sosc4s', 2, 'R', '1h90e2frullvk', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'user_name', 'N', 'N', 'VF', 'User name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'Y', 'Y', 1, 1, 'grid_left', 0, 'L', '', 0, 'L', '9gba8zpqcnwg', 0, 'L', '1s9mtebmfoo0o', 1, 1, 0, 'L', '1kfjzfu4tbb4s', 0, 'L', '1op6wuzxu9fo', 1),
('preferences_lookandfeel', 'users', 'user_id', 'N', 'N', 'RK', 'User identifier', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'timezone_id', 'N', 'Y', 'DD', 'Timezone', 1, '225', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'L', 'bi2qxal31txucckgc4sosc4s', 3, 'L', '1h90e2frullvk', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'theme_id', 'N', 'N', 'DD', 'Theme', 1, 'default', 'global_themes', 'theme_id', 'theme_name', ' order by theme_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', 'hi2u1ickxmh340ssog40w0k0', 1, 'L', '10ragq2617itc', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'skin_id', 'N', 'N', 'DD', 'Skin', 1, 'default', 'global_skins', 'skin_id', 'skin_name', ' order by skin_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', 'dxodpktw7tsg', 0, 'R', '2brr1b6lkeasw', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'send_welcome_email', 'N', 'Y', 'CH', 'Send welcome email', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 2, 'L', '13qfxwi7vfi8w', 0, 'L', '', 0, 'L', 'kfpueqebytc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'salutation', 'N', 'N', 'TE', 'Salutation', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '235c8hd439voo', 0, 'L', 'sif2w2u11r4g', 0, 0, 0, 'L', '1cz0xswt9tq84', 0, 'L', 'vhl12f6951c4', 0),
('preferences_lookandfeel', 'users', 'reset_password', 'N', 'Y', 'CH', 'Reset password', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 3, 'L', '13qfxwi7vfi8w', 0, 'L', '', 0, 'R', 'kfpueqebytc0', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'private_phone', 'N', 'N', 'TE', 'Private phone', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '1j2a5w3hftwgg', 0, 'L', '1q6htfo3inesk', 0, 0, 0, 'L', '1pz3r2tgoyo0s', 0, 'L', 'sr1hn2m5y684', 0),
('preferences_lookandfeel', 'users', 'private_mobile', 'N', 'N', 'TE', 'Private mobile', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', '1j2a5w3hftwgg', 0, 'R', '1q6htfo3inesk', 0, 0, 0, 'R', '1pz3r2tgoyo0s', 0, 'R', 'sr1hn2m5y684', 0),
('preferences_lookandfeel', 'users', 'private_email', 'N', 'N', 'WM', 'Private email', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', '1j2a5w3hftwgg', 0, 'R', '1q6htfo3inesk', 0, 0, 0, 'R', '1pz3r2tgoyo0s', 0, 'R', 'sr1hn2m5y684', 0),
('preferences_lookandfeel', 'users', 'password', 'N', 'N', 'TE', 'Password', 1, '', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'phone', 'N', 'N', 'TE', 'Phone', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 5, 'grid_left', 0, 'L', '', 0, 'L', '235c8hd439voo', 0, 'L', 'sif2w2u11r4g', 0, 5, 0, 'L', '1cz0xswt9tq84', 0, 'L', 'vhl12f6951c4', 5),
('preferences_lookandfeel', 'users', 'nbrecords', 'N', 'N', 'DD', 'Lines displayed', 1, '10', 'global_lines', 'line_id', 'line_name', 'order by line_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', '8xfiiba91u5qossows8c4g0s', 1, 'R', '12238nyd9hxc0', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'manager_id', 'N', 'N', 'RR', 'Manager', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 2, 'R', '13qfxwi7vfi8w', 0, 'R', '235c8hd439voo', 0, 'R', 'sif2w2u11r4g', 5, 0, 0, 'R', '1cz0xswt9tq84', 0, 'R', 'vhl12f6951c4', 0),
('preferences_lookandfeel', 'users', 'locale_id', 'N', 'N', 'DD', 'Locale', 1, 'en_US', 'global_locales', 'locale_id', 'locale_name', ' order by locale_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', '8xfiiba91u5qossows8c4g0s', 0, 'R', '12238nyd9hxc0', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'last_password_change', 'N', 'N', 'TS', 'Last password change', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'R', '1lhqls5x4yv48', 0, 'R', 'kfpueqebytc0', 0, 0, 0, 'R', '1lmo16svlpdwo', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'last_name', 'N', 'N', 'VF', 'Last name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 3, 3, 'grid_left', 0, 'L', '', 0, 'R', '235c8hd439voo', 0, 'R', 'sif2w2u11r4g', 3, 3, 0, 'R', '1cz0xswt9tq84', 0, 'R', 'vhl12f6951c4', 3),
('preferences_lookandfeel', 'users', 'last_login', 'N', 'N', 'TS', 'Last login', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '1lhqls5x4yv48', 0, 'L', 'kfpueqebytc0', 0, 0, 0, 'L', '1lmo16svlpdwo', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'language_id', 'N', 'N', 'DD', 'Language', 1, 'en', 'global_languages', 'language_id', 'language_name', ' order by language_id', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', 'bi2qxal31txucckgc4sosc4s', 1, 'L', '1h90e2frullvk', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'is_salespeople', 'N', 'N', 'CH', 'Sales people', 1, 'N', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '13qfxwi7vfi8w', 0, 'R', '235c8hd439voo', 0, 'R', 'sif2w2u11r4g', 0, 0, 0, 'R', '1cz0xswt9tq84', 0, 'R', 'vhl12f6951c4', 0),
('preferences_lookandfeel', 'users', 'full_name', 'N', 'N', 'TE', 'Full name', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'first_names', 'N', 'N', 'VF', 'First name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 2, 2, 'grid_left', 0, 'L', '', 0, 'L', '235c8hd439voo', 0, 'L', 'sif2w2u11r4g', 2, 2, 0, 'L', '1cz0xswt9tq84', 0, 'L', 'vhl12f6951c4', 2),
('preferences_lookandfeel', 'users', 'fax', 'N', 'N', 'TE', 'Fax', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '235c8hd439voo', 0, 'L', 'sif2w2u11r4g', 0, 0, 0, 'L', '1cz0xswt9tq84', 0, 'L', 'vhl12f6951c4', 0),
('preferences_lookandfeel', 'users', 'email', 'N', 'N', 'WM', 'Email', 1, '', '', '', '', '', 'N', 'N', 'Y', 'Y', 'Y', 0, 7, 'grid_left', 0, 'L', '', 0, 'L', '235c8hd439voo', 0, 'L', 'sif2w2u11r4g', 0, 7, 0, 'L', '1cz0xswt9tq84', 0, 'L', 'vhl12f6951c4', 7),
('preferences_lookandfeel', 'users', 'department_id', 'N', 'N', 'RR', 'Department', 1, '', 'departments', 'department_id', 'department_name', '', 'N', 'N', 'N', 'N', 'Y', 4, 4, 'grid_left', 3, 'R', '13qfxwi7vfi8w', 0, 'R', '235c8hd439voo', 0, 'R', 'sif2w2u11r4g', 4, 4, 0, 'R', '1cz0xswt9tq84', 0, 'R', 'vhl12f6951c4', 4),
('preferences_lookandfeel', 'users', 'currency_id', 'N', 'N', 'DD', 'Currency', 1, 'USD', 'global_currencies', 'currency_id', 'currency_name', ' order by currency_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', 'bi2qxal31txucckgc4sosc4s', 2, 'L', '1h90e2frullvk', 0, 0, 0, 'R', '13z2ehlofjuow', 0, 'R', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'created', 'N', 'N', 'TS', 'Created', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '1lhqls5x4yv48', 0, 'L', '', 0, 0, 0, 'L', '1lmo16svlpdwo', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'birthdate', 'N', 'N', 'DA', 'Date of birth', 1, '0000-00-00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '1j2a5w3hftwgg', 0, 'L', '1q6htfo3inesk', 0, 0, 0, 'L', '1pz3r2tgoyo0s', 0, 'L', 'sr1hn2m5y684', 0),
('preferences_lookandfeel', 'users', 'assistant_id', 'N', 'N', 'RR', 'Assistant', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 1, 'R', '13qfxwi7vfi8w', 0, 'R', '235c8hd439voo', 0, 'R', 'sif2w2u11r4g', 6, 0, 0, 'R', '1cz0xswt9tq84', 0, 'R', 'vhl12f6951c4', 0),
('preferences_lookandfeel', 'users', 'app_name', 'N', 'N', 'DD', 'Default application', 1, 'api', 'db_applications', 'app_name', 'app_label', 'where is_visible = "Y" and status_id = "A" order by app_label', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '8xfiiba91u5qossows8c4g0s', 1, 'L', '12238nyd9hxc0', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'note', 'N', 'N', 'ML', 'Note', 5, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '294wh86uphj4g', 0, 'L', '1ixcu5lf30asg', 0, 0, 0, 'L', 'cqkdsoiy8hwg', 0, 'L', 'dxofjnamwhs0', 0),
('preferences_lookandfeel', 'users', 'mobile', 'N', 'N', 'TE', 'Mobile', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 6, 'grid_left', 0, 'L', '', 0, 'L', '235c8hd439voo', 0, 'L', 'sif2w2u11r4g', 0, 6, 0, 'L', '1cz0xswt9tq84', 0, 'L', 'vhl12f6951c4', 6),
('preferences_lookandfeel', 'users', 'created_by', 'N', 'N', 'RR', 'Created by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'charset_id', 'N', 'N', 'DD', 'Character set', 1, 'UTF-8', 'global_charsets', 'charset_id', 'charset_name', 'order by charset_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', 'bi2qxal31txucckgc4sosc4s', 1, 'R', '1h90e2frullvk', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'locale_time_id', 'N', 'N', 'DD', 'Format time', 1, 'en_US', 'global_locales_time', 'time_id', 'time_label', ' order by time_label', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'R', 'bi2qxal31txucckgc4sosc4s', 3, 'R', '1h90e2frullvk', 0, 0, 0, 'L', '13z2ehlofjuow', 0, 'L', 'da9w2y9gqxkc', 0),
('preferences_lookandfeel', 'users', 'title', 'N', 'N', 'TE', 'Title', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', '235c8hd439voo', 0, 'R', 'sif2w2u11r4g', 0, 0, 0, 'R', '1cz0xswt9tq84', 0, 'R', 'vhl12f6951c4', 0),
('preferences_lookandfeel', 'users', 'updated_by', 'N', 'N', 'RR', 'Updated by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_lookandfeel', 'users', 'status_id', 'N', 'N', 'DD', 'User status', 1, 'A', 'users_statuses', 'status_id', 'status_name', 'where status_id in ("A","D") order by status_name', 'N', 'N', 'Y', 'N', 'Y', 5, 8, 'grid_left', 1, 'L', '13qfxwi7vfi8w', 0, 'R', '9gba8zpqcnwg', 0, 'R', '1s9mtebmfoo0o', 0, 0, 0, 'R', '1bwu9iw9qois8', 0, 'R', '1lp4pvgw4f8k0', 8),
('preferences_lookandfeel', 'users', 'updated', 'N', 'N', 'TS', 'Updated', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'R', '1lhqls5x4yv48', 0, 'R', '', 0, 0, 0, 'R', '1lmo16svlpdwo', 0, 'L', '', 0);


DELETE FROM db_blocks where app_name = 'preferences_profile';
INSERT INTO `db_blocks` (`app_name`, `form_name`, `block_id`, `block_name`, `is_title`, `columns`, `block_sequence`) VALUES
('preferences_profile', 'edit', '26y2hrgd023o8', 'Footer', 'N', 2, 7),
('preferences_profile', 'edit', '29pudky0xvtwc', 'Note', 'N', 1, 5),
('preferences_profile', 'edit', '1zf2rc8trag0o', 'Body', 'N', 2, 4),
('preferences_profile', 'view', '9l8phqq6ujwo', 'Footer', 'N', 2, 7),
('preferences_profile', 'view', '9dun4w391wso', 'Note', 'N', 1, 5),
('preferences_profile', 'view', '118iuwd6a528g', 'Body', 'N', 2, 4),
('preferences_profile', 'view', 'tqrgvar474g8', 'Header', 'N', 2, 2),
('preferences_profile', 'edit', '1yro7vjsl4ysw', 'Header', 'N', 2, 2),
('preferences_profile', 'popup_view', 'c5mj0n6xfhko', 'Body', 'N', 2, 4),
('preferences_profile', 'popup_view', 'ss9txl6ke6oc', 'Note', 'N', 1, 5),
('preferences_profile', 'popup_edit', '1pxj7dkwrcg0', 'Header', 'N', 2, 2),
('preferences_profile', 'popup_view', 'r3wyomxv1m8s', 'Header', 'N', 2, 2),
('preferences_profile', 'popup_edit', '2bszdlp7ppes4', 'Body', 'N', 2, 4),
('preferences_profile', 'popup_edit', '1lstr1vwvfogg', 'Note', 'N', 1, 5);

DELETE FROM db_fields where app_name = 'preferences_profile';
INSERT INTO `db_fields` (`app_name`, `table_name`, `field_name`, `is_custom`, `is_computed`, `field_type`, `field_label`, `field_height`, `field_default`, `related_table`, `related_id`, `related_name`, `related_filter`, `is_search`, `is_readonly`, `is_mandatory`, `is_unique`, `is_visible`, `search_sequence`, `result_sequence`, `result_class`, `bulk_sequence`, `bulk_side`, `bulk_block_id`, `view_sequence`, `view_side`, `view_block_id`, `edit_sequence`, `edit_side`, `edit_block_id`, `popup_search_sequence`, `popup_result_sequence`, `popup_view_sequence`, `popup_view_side`, `popup_view_block_id`, `popup_edit_sequence`, `popup_edit_side`, `popup_edit_block_id`, `linked_sequence`) VALUES
('preferences_profile', 'users', 'app_name', 'N', 'N', 'TE', 'App name', 1, 'api', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'assistant_id', 'N', 'N', 'RR', 'Assistant', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 4, 'R', 'tqrgvar474g8', 4, 'R', '1yro7vjsl4ysw', 0, 0, 4, 'R', 'r3wyomxv1m8s', 4, 'R', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'birthdate', 'N', 'N', 'DA', 'Date of birth', 1, '0000-00-00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 4, 'R', '118iuwd6a528g', 4, 'R', '1zf2rc8trag0o', 0, 0, 4, 'R', 'c5mj0n6xfhko', 4, 'R', '2bszdlp7ppes4', 0),
('preferences_profile', 'users', 'confirm_delete', 'N', 'N', 'CH', 'Confirm delete', 1, 'Y', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'created', 'N', 'N', 'TS', 'Created', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 2, 'L', '9l8phqq6ujwo', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'created_by', 'N', 'N', 'RR', 'Created by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'currency_id', 'N', 'N', 'DD', 'Currency', 1, 'USD', 'global_currencies', 'currency_id', 'currency_name', 'order by currency_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'department_id', 'N', 'N', 'RR', 'Department', 1, '', 'departments', 'department_id', 'department_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'email', 'N', 'N', 'WM', 'Email', 1, '', '', '', '', '', 'N', 'N', 'Y', 'Y', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '118iuwd6a528g', 1, 'L', '1zf2rc8trag0o', 0, 0, 1, 'L', 'c5mj0n6xfhko', 1, 'L', '2bszdlp7ppes4', 0),
('preferences_profile', 'users', 'fax', 'N', 'N', 'TE', 'Fax', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 4, 'L', '118iuwd6a528g', 4, 'L', '1zf2rc8trag0o', 0, 0, 4, 'L', 'c5mj0n6xfhko', 4, 'L', '2bszdlp7ppes4', 0),
('preferences_profile', 'users', 'first_names', 'N', 'N', 'TE', 'First name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', 'tqrgvar474g8', 2, 'L', '1yro7vjsl4ysw', 0, 0, 2, 'L', 'r3wyomxv1m8s', 2, 'L', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'full_name', 'N', 'N', 'TE', 'Full name', 1, '', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', 'tqrgvar474g8', 0, 'L', '1yro7vjsl4ysw', 0, 0, 0, 'L', 'r3wyomxv1m8s', 0, 'L', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'is_salespeople', 'N', 'N', 'CH', 'Is salespeople', 1, 'N', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'language_id', 'N', 'N', 'DD', 'Language', 1, 'en', 'global_languages', 'language_id', 'language_name', ' order by language_id', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'last_login', 'N', 'N', 'TS', 'Last login', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 1, 'L', '9l8phqq6ujwo', 1, 'L', '26y2hrgd023o8', 0, 0, 0, 'L', '', 0, 'L', 'jzpcz4pef400', 0),
('preferences_profile', 'users', 'last_name', 'N', 'N', 'TE', 'Last name', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', 'tqrgvar474g8', 2, 'R', '1yro7vjsl4ysw', 0, 0, 2, 'R', 'r3wyomxv1m8s', 2, 'R', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'last_password_change', 'N', 'N', 'TS', 'Last password change', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 1, 'R', '9l8phqq6ujwo', 1, 'R', '26y2hrgd023o8', 0, 0, 0, 'L', '', 0, 'R', 'jzpcz4pef400', 0),
('preferences_profile', 'users', 'locale_id', 'N', 'N', 'DD', 'Locale', 1, 'en_US', '', '', '', ' order by ', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'manager_id', 'N', 'N', 'RR', 'Manager', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 4, 'L', 'tqrgvar474g8', 4, 'L', '1yro7vjsl4ysw', 0, 0, 4, 'L', 'r3wyomxv1m8s', 4, 'L', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'mobile', 'N', 'N', 'TE', 'Mobile', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'L', '118iuwd6a528g', 3, 'L', '1zf2rc8trag0o', 0, 0, 3, 'L', 'c5mj0n6xfhko', 3, 'L', '2bszdlp7ppes4', 0),
('preferences_profile', 'users', 'nbrecords', 'N', 'N', 'TE', 'Nbrecords', 1, '10', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'note', 'N', 'N', 'ML', 'Note', 4, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '9dun4w391wso', 1, 'L', '29pudky0xvtwc', 0, 0, 1, 'L', 'ss9txl6ke6oc', 1, 'L', '1lstr1vwvfogg', 0),
('preferences_profile', 'users', 'password', 'N', 'N', 'TE', 'Password', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'phone', 'N', 'N', 'TE', 'Phone', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'L', '118iuwd6a528g', 2, 'L', '1zf2rc8trag0o', 0, 0, 2, 'L', 'c5mj0n6xfhko', 2, 'L', '2bszdlp7ppes4', 0),
('preferences_profile', 'users', 'private_email', 'N', 'N', 'TE', 'Private email', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', '118iuwd6a528g', 1, 'R', '1zf2rc8trag0o', 0, 0, 1, 'R', 'c5mj0n6xfhko', 1, 'R', '2bszdlp7ppes4', 0),
('preferences_profile', 'users', 'private_mobile', 'N', 'N', 'TE', 'Private mobile', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'R', '118iuwd6a528g', 3, 'R', '1zf2rc8trag0o', 0, 0, 3, 'R', 'c5mj0n6xfhko', 3, 'R', '2bszdlp7ppes4', 0),
('preferences_profile', 'users', 'private_phone', 'N', 'N', 'TE', 'Private phone', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', '118iuwd6a528g', 2, 'R', '1zf2rc8trag0o', 0, 0, 2, 'R', 'c5mj0n6xfhko', 2, 'R', '2bszdlp7ppes4', 0),
('preferences_profile', 'users', 'salespeople', 'N', 'N', 'CH', 'Salespeople', 1, 'N', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'salutation', 'N', 'N', 'TE', 'Salutation', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'L', 'tqrgvar474g8', 3, 'L', '1yro7vjsl4ysw', 0, 0, 3, 'L', 'r3wyomxv1m8s', 3, 'L', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'skin_id', 'N', 'N', 'DD', 'Skin', 1, 'default', '', '', '', ' order by ', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'status_id', 'N', 'N', 'DD', 'Status', 1, 'A', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'theme_id', 'N', 'N', 'DD', 'Theme', 1, 'default', '', '', '', ' order by ', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'timezone_id', 'N', 'Y', 'DD', 'Timezone', 1, '225', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'title', 'N', 'N', 'TE', 'Title', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 3, 'R', 'tqrgvar474g8', 3, 'R', '1yro7vjsl4ysw', 0, 0, 3, 'R', 'r3wyomxv1m8s', 3, 'R', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'updated', 'N', 'N', 'TS', 'Updated', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 2, 'R', '9l8phqq6ujwo', 0, 'R', '', 0, 0, 0, 'L', '', 0, 'R', '', 0),
('preferences_profile', 'users', 'updated_by', 'N', 'N', 'RR', 'Updated by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('preferences_profile', 'users', 'user_id', 'N', 'N', 'RK', 'User identifier', 1, '', '', '', '', '', 'N', 'Y', 'N', 'Y', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', 'tqrgvar474g8', 1, 'R', '1yro7vjsl4ysw', 0, 0, 1, 'R', 'r3wyomxv1m8s', 1, 'R', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'user_name', 'N', 'N', 'TE', 'User name', 1, '', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', 'tqrgvar474g8', 1, 'L', '1yro7vjsl4ysw', 0, 0, 1, 'L', 'r3wyomxv1m8s', 1, 'L', '1pxj7dkwrcg0', 0),
('preferences_profile', 'users', 'user_status', 'N', 'N', 'CH', 'User status', 1, 'A', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0);

DELETE FROM db_blocks where app_name = 'support_faqs';
INSERT INTO `db_blocks` (`app_name`, `form_name`, `block_id`, `block_name`, `is_title`, `columns`, `block_sequence`) VALUES
('support_faqs', 'bulk', 'lo2dyy4xm1w4', 'Bulk', 'N', 2, 2),
('support_faqs', 'edit', '1z8x76i8wqxww', 'Note', 'N', 1, 4),
('support_faqs', 'edit', '4xq1vkxgqc0s', 'Header', 'N', 1, 1),
('support_faqs', 'edit', 'bn5ivdwa540g', 'Main', 'N', 2, 3),
('support_faqs', 'popup_edit', '1budqhh47la8s', 'Header', 'N', 1, 1),
('support_faqs', 'popup_edit', '1ib6sqac2itc4', 'Note', 'N', 1, 4),
('support_faqs', 'popup_edit', '1pxvkbx6v7ggs', 'Main', 'N', 2, 3),
('support_faqs', 'popup_view', 'cak2c2ycv9s8', 'Main', 'N', 2, 3),
('support_faqs', 'popup_view', 't8agsawnl7kg', 'Header', 'N', 1, 1),
('support_faqs', 'view', '141j8x4nsqcgc', 'Footer', 'N', 2, 6),
('support_faqs', 'view', '19r8qitiobusk', 'Header', 'N', 1, 1),
('support_faqs', 'view', '1hv6bmfw4yv48', 'Main', 'N', 2, 3),
('support_faqs', 'view', 'trzz2kk7iu8g', 'Note', 'N', 1, 4);

DELETE FROM db_fields where app_name = 'support_faqs';
INSERT INTO `db_fields` (`app_name`, `table_name`, `field_name`, `is_custom`, `is_computed`, `field_type`, `field_label`, `field_height`, `field_default`, `related_table`, `related_id`, `related_name`, `related_filter`, `is_search`, `is_readonly`, `is_mandatory`, `is_unique`, `is_visible`, `search_sequence`, `result_sequence`, `result_class`, `bulk_sequence`, `bulk_side`, `bulk_block_id`, `view_sequence`, `view_side`, `view_block_id`, `edit_sequence`, `edit_side`, `edit_block_id`, `popup_search_sequence`, `popup_result_sequence`, `popup_view_sequence`, `popup_view_side`, `popup_view_block_id`, `popup_edit_sequence`, `popup_edit_side`, `popup_edit_block_id`, `linked_sequence`) VALUES
('support_faqs', 'backoffice_support_faqs', 'category_id', 'N', 'N', 'DD', 'Category', 1, '', 'backoffice_support_faqs_categories', 'category_id', 'category_name', 'order by category_sequence', 'N', 'Y', 'Y', 'N', 'Y', 2, 2, 'grid_left', 1, 'L', 'lo2dyy4xm1w4', 1, 'L', '1hv6bmfw4yv48', 1, 'L', 'bn5ivdwa540g', 2, 2, 1, 'L', 'cak2c2ycv9s8', 1, 'L', '1pxvkbx6v7ggs', 2),
('support_faqs', 'backoffice_support_faqs', 'created', 'N', 'N', 'TS', 'Created', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 1, 'L', '141j8x4nsqcgc', 0, 'L', '', 0, 0, 0, 'L', '18ld15zxsvk04', 0, 'L', '', 0),
('support_faqs', 'backoffice_support_faqs', 'created_by', 'N', 'N', 'DD', 'Created by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('support_faqs', 'backoffice_support_faqs', 'edition_id', 'N', 'N', 'DD', 'Edition', 1, '', 'global_editions', 'edition_id', 'edition_name', '', 'N', 'N', 'N', 'N', 'Y', 3, 3, 'grid_left', 1, 'R', 'lo2dyy4xm1w4', 1, 'R', '1hv6bmfw4yv48', 1, 'R', 'bn5ivdwa540g', 3, 3, 1, 'R', 'cak2c2ycv9s8', 1, 'R', '1pxvkbx6v7ggs', 3),
('support_faqs', 'backoffice_support_faqs', 'faq_id', 'N', 'N', 'RK', 'Faq identifier', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('support_faqs', 'backoffice_support_faqs', 'is_active', 'N', 'N', 'CH', 'Is active', 1, 'A', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 2, 'L', 'lo2dyy4xm1w4', 0, 'L', '', 2, 'L', 'bn5ivdwa540g', 0, 0, 0, 'L', '', 2, 'R', '1pxvkbx6v7ggs', 0),
('support_faqs', 'backoffice_support_faqs', 'note', 'N', 'N', 'ML', 'Note', 20, '', '', '', '', '', 'Y', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 1, 'L', 'trzz2kk7iu8g', 1, 'L', '1z8x76i8wqxww', 0, 0, 0, 'L', 'vitj3t2oglws', 1, 'L', '1ib6sqac2itc4', 0),
('support_faqs', 'backoffice_support_faqs', 'subject', 'N', 'N', 'VF', 'Subject', 1, '', '', '', '', '', 'Y', 'N', 'Y', 'N', 'Y', 1, 1, 'grid_left', 0, 'L', '', 1, 'L', '19r8qitiobusk', 1, 'L', '4xq1vkxgqc0s', 1, 1, 1, 'L', 't8agsawnl7kg', 1, 'L', '1budqhh47la8s', 1),
('support_faqs', 'backoffice_support_faqs', 'updated', 'N', 'N', 'TS', 'Updated', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 1, 'R', '141j8x4nsqcgc', 0, 'R', '', 0, 0, 0, 'L', '', 0, 'R', '', 0),
('support_faqs', 'backoffice_support_faqs', 'updated_by', 'N', 'N', 'DD', 'Updated by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'R', '', 0, 'R', '', 0, 0, 0, 'R', '', 0, 'L', '', 0),
('support_faqs', 'backoffice_support_faqs', 'user_id', 'N', 'N', 'DD', 'Owner', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 2, 'R', 'lo2dyy4xm1w4', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0);

DELETE FROM db_blocks where app_name = 'support_tickets';
INSERT INTO `db_blocks` (`app_name`, `form_name`, `block_id`, `block_name`, `is_title`, `columns`, `block_sequence`) VALUES
('support_tickets', 'view', 'lj50b4cuhcgc', 'Footer', 'N', 2, 6),
('support_tickets', 'view', '1223a1n1tsogs', 'Note', 'N', 1, 4),
('support_tickets', 'edit', 'co3uo1a4t48o', 'Header', 'N', 1, 1),
('support_tickets', 'edit', '2be7en9edd348', 'Main', 'N', 2, 3),
('support_tickets', 'popup_edit', 'ibcndsd8tm8s', 'Header', 'N', 1, 1),
('support_tickets', 'popup_view', '45e4r22e9okk', 'Header', 'N', 1, 1),
('support_tickets', 'popup_edit', '11fx2z360hr4k', 'Note', 'N', 1, 4),
('support_tickets', 'popup_view', '27mpjc01xrfo0', 'Main', 'N', 2, 3),
('support_tickets', 'popup_edit', 'miuzp8ixiyo4', 'Main', 'N', 2, 3),
('support_tickets', 'edit', 'm5b7hbww1kgs', 'Note', 'N', 1, 4),
('support_tickets', 'view', 'mlbohio1mi8o', 'Main', 'N', 2, 3),
('support_tickets', 'view', '1cdwjf8bx9lw', 'Header', 'N', 1, 1),
('support_tickets', 'bulk', '1a2btyu0dyrog', 'Bulk', 'N', 2, 2);

DELETE FROM db_fields where app_name = 'support_tickets';
INSERT INTO `db_fields` (`app_name`, `table_name`, `field_name`, `is_custom`, `is_computed`, `field_type`, `field_label`, `field_height`, `field_default`, `related_table`, `related_id`, `related_name`, `related_filter`, `is_search`, `is_readonly`, `is_mandatory`, `is_unique`, `is_visible`, `search_sequence`, `result_sequence`, `result_class`, `bulk_sequence`, `bulk_side`, `bulk_block_id`, `view_sequence`, `view_side`, `view_block_id`, `edit_sequence`, `edit_side`, `edit_block_id`, `popup_search_sequence`, `popup_result_sequence`, `popup_view_sequence`, `popup_view_side`, `popup_view_block_id`, `popup_edit_sequence`, `popup_edit_side`, `popup_edit_block_id`, `linked_sequence`) VALUES
('support_tickets', 'backoffice_support_tickets', 'status_id', 'N', 'N', 'DD', 'Status', 1, '', 'backoffice_support_tickets_statuses', 'status_id', 'status_name', '', 'N', 'N', 'N', 'N', 'Y', 4, 1, 'grid_left', 1, 'R', '1a2btyu0dyrog', 1, 'R', 'mlbohio1mi8o', 1, 'R', '2be7en9edd348', 3, 1, 1, 'R', '27mpjc01xrfo0', 1, 'R', 'miuzp8ixiyo4', 1),
('support_tickets', 'backoffice_support_tickets', 'subject', 'N', 'N', 'VF', 'Subject', 1, '', '', '', '', '', 'Y', 'N', 'Y', 'N', 'Y', 1, 2, 'grid_left', 0, 'L', '', 1, 'L', '1cdwjf8bx9lw', 1, 'L', 'co3uo1a4t48o', 1, 2, 1, 'L', '45e4r22e9okk', 1, 'L', 'ibcndsd8tm8s', 2),
('support_tickets', 'backoffice_support_tickets', 'note', 'N', 'N', 'ML', 'Note', 10, '', '', '', '', '', 'Y', 'N', 'Y', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '1223a1n1tsogs', 1, 'L', 'm5b7hbww1kgs', 0, 0, 0, 'L', '27gjtdaiok4k4', 1, 'L', '11fx2z360hr4k', 0),
('support_tickets', 'backoffice_support_tickets', 'due_date', 'N', 'N', 'DA', 'Due date', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '1a2btyu0dyrog', 0, 'L', 'mlbohio1mi8o', 0, 'L', '2be7en9edd348', 0, 0, 0, 'L', '27mpjc01xrfo0', 0, 'L', 'miuzp8ixiyo4', 0),
('support_tickets', 'backoffice_support_tickets', 'priority_id', 'N', 'N', 'DD', 'Priority', 1, '', 'backoffice_support_tickets_priorities', 'priority_id', 'priority_name', '', 'N', 'N', 'N', 'N', 'Y', 5, 4, 'grid_left', 2, 'L', '1a2btyu0dyrog', 2, 'L', 'mlbohio1mi8o', 2, 'L', '2be7en9edd348', 4, 4, 2, 'L', '27mpjc01xrfo0', 2, 'L', 'miuzp8ixiyo4', 4),
('support_tickets', 'backoffice_support_tickets', 'created', 'N', 'N', 'TS', 'Created', 1, '', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 1, 'L', 'lj50b4cuhcgc', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('support_tickets', 'backoffice_support_tickets', 'created_by', 'N', 'N', 'RR', 'Created by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('support_tickets', 'backoffice_support_tickets', 'company_id', 'N', 'N', 'DD', 'Company', 1, '', 'company', 'company_id', 'company_name', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', 'mlbohio1mi8o', 0, 'R', '2be7en9edd348', 0, 0, 0, 'R', '27mpjc01xrfo0', 0, 'R', 'miuzp8ixiyo4', 0),
('support_tickets', 'backoffice_support_tickets', 'updated', 'N', 'N', 'TS', 'Updated', 1, '', '', '', '', '', 'N', 'Y', 'N', 'N', 'Y', 0, 5, 'grid_center', 0, 'L', '', 1, 'R', 'lj50b4cuhcgc', 0, 'L', '', 0, 5, 0, 'L', '', 0, 'L', '', 5),
('support_tickets', 'backoffice_support_tickets', 'updated_by', 'N', 'N', 'RR', 'Updated by', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 6, 0, 'L', '', 0, 'L', '', 6),
('support_tickets', 'backoffice_support_tickets', 'category_id', 'N', 'N', 'DD', 'Category', 1, '', 'backoffice_support_tickets_categories', 'category_id', 'category_name', 'order by category_sequence', 'N', 'N', 'Y', 'N', 'Y', 3, 3, 'grid_left', 1, 'L', '1a2btyu0dyrog', 1, 'L', 'mlbohio1mi8o', 1, 'L', '2be7en9edd348', 2, 3, 1, 'L', '27mpjc01xrfo0', 1, 'L', 'miuzp8ixiyo4', 3),
('support_tickets', 'backoffice_support_tickets', 'email', 'N', 'N', 'WM', 'Email', 1, '', '', '', '', '', 'Y', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 2, 'R', 'mlbohio1mi8o', 0, 'R', '2be7en9edd348', 0, 0, 0, 'R', '27mpjc01xrfo0', 0, 'R', 'miuzp8ixiyo4', 0),
('support_tickets', 'backoffice_support_tickets', 'edition_id', 'N', 'N', 'DD', 'Edition', 1, '', 'backoffice_support_tickets_editions', 'edition_id', 'edition_name', '', 'N', 'Y', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'R', '1a2btyu0dyrog', 0, 'R', 'mlbohio1mi8o', 0, 'R', '2be7en9edd348', 0, 0, 0, 'R', '27mpjc01xrfo0', 0, 'R', 'miuzp8ixiyo4', 0),
('support_tickets', 'backoffice_support_tickets', 'user_id', 'N', 'N', 'DD', 'Owner', 1, '', 'users', 'user_id', 'full_name', '', 'N', 'Y', 'N', 'N', 'Y', 6, 6, 'grid_left', 2, 'R', '1a2btyu0dyrog', 0, 'R', 'mlbohio1mi8o', 2, 'R', '2be7en9edd348', 5, 7, 2, 'R', '27mpjc01xrfo0', 2, 'R', 'miuzp8ixiyo4', 7),
('support_tickets', 'backoffice_support_tickets', 'ticket_id', 'N', 'N', 'RK', 'Ticket identifier', 1, '', '', '', '', '', 'N', 'Y', 'N', 'Y', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'R', 'mlbohio1mi8o', 0, 'R', '2be7en9edd348', 0, 0, 0, 'R', '27mpjc01xrfo0', 0, 'R', 'miuzp8ixiyo4', 0),
('support_tickets', 'backoffice_support_tickets', 'historic', 'N', 'N', 'ML', 'Historic', 20, '', '', '', '', '', 'Y', 'Y', 'N', 'N', 'Y', 2, 0, 'grid_left', 0, 'L', '', 1, 'L', '1223a1n1tsogs', 2, 'L', 'm5b7hbww1kgs', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('support_tickets', 'backoffice_support_tickets', 'appshore_version', 'N', 'N', 'DA', 'Appshore version', 1, '0000-00-00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0);

delete from db_blocks where app_name = 'webmail';
INSERT INTO `db_blocks` (`app_name`, `form_name`, `block_id`, `block_name`, `is_title`, `columns`, `block_sequence`) VALUES
('webmail', 'view', 'de3ygur1wgmckkkkg44g0ow4', 'Subject', 'N', 1, 6),
('webmail', 'bulk', '10a0vzsn8jmu5', 'Bulk', 'N', 2, 2),
('webmail', 'popup_view', '18hnj62icuujr', 'Main', 'N', 1, 1),
('webmail', 'edit', 'tluh7ih8uyv4', 'To', 'N', 1, 3),
('webmail', 'edit', '1d09nxy4tngg0', 'CC-Bcc', 'N', 2, 5),
('webmail', 'view', '2k4gzds0ud55q8wos8sksw4g', 'CC-Bcc', 'N', 2, 5),
('webmail', 'popup_edit', 'hqeeu9ndagz8', 'Main', 'N', 1, 3),
('webmail', 'view', '1c0lcn5bmmkx68sosccs00c4o', 'Attachement', 'N', 1, 8),
('webmail', 'edit', 'ixj2n93p8c1s', 'Message', 'N', 1, 8),
('webmail', 'edit', 'usyiyh819a0w', 'Header', 'N', 2, 2),
('webmail', 'edit', '74zpg30isnrh2cws0wgk48wo', 'Subject', 'N', 1, 6),
('webmail', 'edit', '1hqsns73yrizwg4wg8888wosc', 'Attachement', 'N', 1, 7),
('webmail', 'view', '17rlwh26sbqh8g4scgk40s00g', 'Message', 'N', 1, 7),
('webmail', 'view', 'ti5vmf5qzdqj48s8gk4csow', 'To', 'N', 1, 3),
('webmail', 'view', 'f4ee8xyybqw34swkc4wgc8cg', 'Header', 'N', 2, 2);

delete from db_fields where app_name = 'webmail';
INSERT INTO `db_fields` (`app_name`, `table_name`, `field_name`, `is_custom`, `is_computed`, `field_type`, `field_label`, `field_height`, `field_default`, `related_table`, `related_id`, `related_name`, `related_filter`, `is_search`, `is_readonly`, `is_mandatory`, `is_unique`, `is_visible`, `search_sequence`, `result_sequence`, `result_class`, `bulk_sequence`, `bulk_side`, `bulk_block_id`, `view_sequence`, `view_side`, `view_block_id`, `edit_sequence`, `edit_side`, `edit_block_id`, `popup_search_sequence`, `popup_result_sequence`, `popup_view_sequence`, `popup_view_side`, `popup_view_block_id`, `popup_edit_sequence`, `popup_edit_side`, `popup_edit_block_id`, `linked_sequence`) VALUES
('webmail', 'webmail', 'mail_id', 'N', 'N', 'RK', 'Mail', 1, '', '', '', '', '', 'N', 'N', 'Y', 'N', 'Y', -1, -1, 'grid_left', -1, 'L', '', 0, 'L', '', -1, 'L', '', -1, -1, -1, 'L', '', 0, 'L', '', -1),
('webmail', 'webmail', 'user_id', 'N', 'N', 'DD', 'Owner', 1, '', 'users', 'user_id', 'full_name', ' order by full_name', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'folder_id', 'N', 'N', 'DD', 'Folder', 1, '', 'webmail_folders', 'folder_id', 'folder_name', ' order by folder_name', 'N', 'N', 'N', 'N', 'Y', 0, 5, 'grid_left', 1, 'R', '10a0vzsn8jmu5', 0, 'L', 'f4ee8xyybqw34swkc4wgc8cg', 0, 'L', 'usyiyh819a0w', 3, 3, 0, 'L', '', 0, 'L', '', 5),
('webmail', 'webmail', 'mail_size', 'N', 'N', 'DS', 'Size', 1, '0', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 3, 'grid_right', 0, 'L', '', 2, 'R', 'f4ee8xyybqw34swkc4wgc8cg', 0, 'R', 'usyiyh819a0w', 0, 0, 0, 'L', '', 0, 'L', '', 3),
('webmail', 'webmail', 'isread', 'N', 'N', 'CH', 'Mark as read', 1, 'N', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 1, 'L', '10a0vzsn8jmu5', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'bound', 'N', 'N', 'EN', 'Bound', 1, 'O', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_center', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'mail_from', 'N', 'N', 'TE', 'From', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 3, 0, 'grid_left', 0, 'L', '', 1, 'L', 'f4ee8xyybqw34swkc4wgc8cg', 1, 'L', 'usyiyh819a0w', 2, 2, 1, 'L', '18hnj62icuujr', 2, 'L', 'hqeeu9ndagz8', 0),
('webmail', 'webmail', 'mail_to', 'N', 'N', 'EM', 'To', 2, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 2, 1, 'grid_left', 0, 'L', '', 1, 'L', 'ti5vmf5qzdqj48s8gk4csow', 1, 'L', 'tluh7ih8uyv4', 0, 0, 2, 'L', '18hnj62icuujr', 1, 'L', 'hqeeu9ndagz8', 1),
('webmail', 'webmail', 'reply_to', 'N', 'N', 'ML', 'Reply to', 4, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'mail_cc', 'N', 'N', 'EM', 'Cc', 2, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '2k4gzds0ud55q8wos8sksw4g', 1, 'L', '1d09nxy4tngg0', 0, 0, 0, 'L', '18hnj62icuujr', 0, 'L', '', 0),
('webmail', 'webmail', 'mail_bcc', 'N', 'N', 'EM', 'Bcc', 2, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'R', '2k4gzds0ud55q8wos8sksw4g', 1, 'R', '1d09nxy4tngg0', 0, 0, 0, 'L', '18hnj62icuujr', 0, 'L', '', 0),
('webmail', 'webmail', 'mail_date', 'N', 'N', 'DT', 'Date', 1, '0000-00-00 00:00:00', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 4, 4, 'grid_center', 0, 'L', '', 2, 'L', 'f4ee8xyybqw34swkc4wgc8cg', 0, 'R', 'usyiyh819a0w', 0, 4, 4, 'L', '18hnj62icuujr', 0, 'L', '', 4),
('webmail', 'webmail', 'type', 'N', 'N', 'TE', 'Type', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'subtype', 'N', 'N', 'TE', 'Subtype', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'encoding', 'N', 'N', 'TE', 'Encoding', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'subject', 'N', 'N', 'VF', 'Subject', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 1, 2, 'grid_left', 0, 'L', '', 1, 'L', 'de3ygur1wgmckkkkg44g0ow4', 1, 'L', '74zpg30isnrh2cws0wgk48wo', 1, 1, 3, 'L', '18hnj62icuujr', 3, 'L', 'hqeeu9ndagz8', 2),
('webmail', 'webmail', 'body_html', 'N', 'N', 'EH', 'Message', 15, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '17rlwh26sbqh8g4scgk40s00g', 1, 'L', 'ixj2n93p8c1s', 0, 0, 5, 'L', '18hnj62icuujr', 4, 'L', 'hqeeu9ndagz8', 0),
('webmail', 'webmail', 'body_text', 'N', 'N', 'ML', 'Body text', 4, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'priority_id', 'N', 'N', 'DD', 'Priority', 1, '', 'webmail_priorities', 'priority_id', 'priority_name', ' order by priority_sequence', 'N', 'N', 'N', 'N', 'Y', 5, 0, 'grid_left', 0, 'L', '', 1, 'R', 'f4ee8xyybqw34swkc4wgc8cg', 1, 'R', 'usyiyh819a0w', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'account_id', 'N', 'N', 'RR', 'Account id', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'contact_id', 'N', 'N', 'RR', 'Contact id', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 0, 'L', '', 0, 'L', '', 0, 0, 0, 'L', '', 0, 'L', '', 0),
('webmail', 'webmail', 'is_attachment', 'N', 'Y', 'AT', 'Attachment', 1, '', '', '', '', '', 'N', 'N', 'N', 'N', 'Y', 0, 0, 'grid_left', 0, 'L', '', 1, 'L', '1c0lcn5bmmkx68sosccs00c4o', 1, 'L', '1hqsns73yrizwg4wg8888wosc', 0, 0, 0, 'L', '', 0, 'L', '', 0);

